version: "3"
services:
    node_latest:
        build:
            context: .
            dockerfile: .docker/Dockerfile-node-latest
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"

    node_7:
        build:
            context: .
            dockerfile: .docker/Dockerfile-node-7
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"

    node_6:
        build:
            context: .
            dockerfile: .docker/Dockerfile-node-6
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"
